### ISSUE TITLE
V0.4 Feedback

### ISSUE THREAD

**Issue by hang15** [CS2103AUG2016-T14-C4/main#79]
**General**
Good use of SLAP and documentation. 
There are still violations of coding standards which can be improved.
Collate files only reflect 3 person when you have 4 members. Please update even if there are rejected or unused code.

@Skaty 
Empty `@return` `@param` tags
![image](https://cloud.githubusercontent.com/assets/16056698/19834482/3733289a-9e9c-11e6-9b87-9ce836264d92.png)
Proper line break after `@Override`
![image](https://cloud.githubusercontent.com/assets/16056698/19834498/cb2be3c0-9e9c-11e6-98c0-18273c52b0a9.png)

**A0144939R**
Can be refactored to reduce inline comments
![image](https://cloud.githubusercontent.com/assets/16056698/19834634/3e5e4022-9ea2-11e6-9a26-416c4b2deb11.png)
Remove commented code from collate files
![image](https://cloud.githubusercontent.com/assets/16056698/19834638/625af93e-9ea2-11e6-8ae3-f54bba7f477a.png)

**A0153467Y**
There should be a space after `if`, `else`.
![image](https://cloud.githubusercontent.com/assets/16056698/19834587/6ea7b27e-9ea0-11e6-9232-3d5bf139b335.png)
No need for execution after your assertion
![image](https://cloud.githubusercontent.com/assets/16056698/19834617/7fd6a126-9ea1-11e6-88b4-d443383a1013.png)
You can pull out common tests set ups using junit's `setUp`
![image](https://cloud.githubusercontent.com/assets/16056698/19834654/573f0d46-9ea3-11e6-8626-b9feb4a7c6d2.png)

**Comment by Skaty** [comment]
Feedback noted.
